"""Self-contained HTML report for an authentication event's assurance."""

from __future__ import annotations

import html
from typing import Optional

from passkit.policy.model import PolicyDecision
from passkit.zerotrust.scorer import AssuranceScore

_CSS = """
:root{color-scheme:light dark}
body{font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;margin:0;
background:#0d1117;color:#e6edf3}
.wrap{max-width:820px;margin:0 auto;padding:32px 20px}
h1{font-size:22px;margin:0 0 4px}
.sub{color:#8b949e;margin:0 0 24px}
.card{background:#161b22;border:1px solid #30363d;border-radius:10px;
padding:20px;margin:16px 0}
.gauge{display:flex;align-items:center;gap:20px}
.score{font-size:48px;font-weight:700}
.level{font-size:14px;padding:4px 12px;border-radius:999px;font-weight:600}
.aal3{background:#1f6f43;color:#d3f9e0}
.aal2{background:#9e6a03;color:#ffe9b3}
.aal1{background:#8b2c2c;color:#ffd7d7}
table{width:100%;border-collapse:collapse;margin-top:8px}
th,td{text-align:left;padding:8px 6px;border-bottom:1px solid #30363d;font-size:14px}
th{color:#8b949e;font-weight:600}
.pts-pos{color:#3fb950}.pts-zero{color:#8b949e}.pts-neg{color:#f85149}
.bar{height:8px;background:#30363d;border-radius:4px;overflow:hidden;margin-top:6px}
.bar>i{display:block;height:100%;background:linear-gradient(90deg,#3fb950,#2ea043)}
.decision{font-weight:700;font-size:16px}
.allow{color:#3fb950}.deny{color:#f85149}
.caveat{color:#d29922}
ul{margin:6px 0;padding-left:20px}
.foot{color:#586069;font-size:12px;margin-top:24px}
code{background:#21262d;padding:1px 5px;border-radius:4px}
"""


def _pts_class(pts: int) -> str:
    if pts > 0:
        return "pts-pos"
    if pts < 0:
        return "pts-neg"
    return "pts-zero"


def render_report(
    score: AssuranceScore,
    *,
    subject: str = "authentication event",
    rp_id: Optional[str] = None,
    origin: Optional[str] = None,
    decision: Optional[PolicyDecision] = None,
) -> str:
    """Render a standalone HTML assurance report (returns an HTML string)."""
    e = html.escape
    aal_class = {1: "aal1", 2: "aal2", 3: "aal3"}[score.level.value]

    rows = []
    for s in score.signals:
        pct = 0 if s.max_points == 0 else max(0, round(100 * s.points / s.max_points))
        rows.append(
            f"<tr><td>{e(s.name)}</td>"
            f'<td class="{_pts_class(s.points)}">{s.points:+d} / {s.max_points}</td>'
            f"<td>{e(s.detail)}"
            f'<div class="bar"><i style="width:{pct}%"></i></div></td></tr>'
        )

    caveats = ""
    if score.caveats:
        items = "".join(f'<li class="caveat">{e(c)}</li>' for c in score.caveats)
        caveats = f'<div class="card"><h3>Caveats</h3><ul>{items}</ul></div>'

    decision_html = ""
    if decision is not None:
        cls = "allow" if decision.allow else "deny"
        verdict = "ALLOW" if decision.allow else "DENY"
        reasons = "".join(f"<li>{e(r)}</li>" for r in decision.reasons)
        matched = "".join(f"<li>{e(m)}</li>" for m in decision.matched)
        decision_html = f"""
        <div class="card">
          <h3>Policy decision — {e(decision.policy_name)}</h3>
          <p class="decision {cls}">{verdict}</p>
          {'<strong>Reasons</strong><ul>' + reasons + '</ul>' if reasons else ''}
          {'<strong>Matched</strong><ul>' + matched + '</ul>' if matched else ''}
        </div>"""

    meta = []
    if rp_id:
        meta.append(f"RP ID <code>{e(rp_id)}</code>")
    if origin:
        meta.append(f"origin <code>{e(origin)}</code>")
    meta_html = " · ".join(meta)

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>passkit assurance report</title>
<style>{_CSS}</style></head>
<body><div class="wrap">
<h1>Assurance report</h1>
<p class="sub">{e(subject)}{' — ' + meta_html if meta_html else ''}</p>
<div class="card">
  <div class="gauge">
    <div class="score">{score.score}<span style="font-size:20px;color:#8b949e">/100</span></div>
    <span class="level {aal_class}">{e(score.level.label)}</span>
  </div>
  <table>
    <tr><th>Signal</th><th>Points</th><th>Detail</th></tr>
    {''.join(rows)}
  </table>
</div>
{caveats}
{decision_html}
<p class="foot">Generated by passkit · open, self-hostable, standards-based
phishing-resistant authentication tooling. Scoring is a risk aid modeled on
NIST SP 800-63B AALs; it is not a formal certification.</p>
</div></body></html>"""


__all__ = ["render_report"]
